import assert from 'node:assert/strict';

export async function checkRewardsAndOffers(browser,base,errors){
  const page=await browser.newPage({viewport:{width:390,height:844},isMobile:true,hasTouch:true});
  page.on('pageerror',e=>errors.push(e.message));page.on('response',r=>{if(r.status()>=400)errors.push(`${r.status()}: ${r.url()}`);});
  await page.addInitScript(()=>{
    if(localStorage.getItem('daily-offers-seeded'))return;
    localStorage.setItem('daily-offers-seeded','true');localStorage.setItem('jelly-coins','5000');
    localStorage.setItem('jelly-profile',JSON.stringify({daily:'2020-01-01',dailyCount:3}));
  });
  await page.goto(base,{waitUntil:'networkidle'});await page.locator('.loading').waitFor({state:'detached'});
  const profile=()=>page.evaluate(()=>JSON.parse(localStorage.getItem('jelly-profile')));
  const coins=async()=>Number((await page.getByTestId('coins').textContent()).replace(/\D/g,''));
  const close=async()=>{await page.getByRole('button',{name:'Закрыть',exact:true}).click();await page.locator('.overlay').waitFor({state:'detached'});};
  const watch=async(button)=>{await button.click();await page.getByRole('dialog',{name:'Имитация рекламы'}).waitFor();await page.locator('.ad-overlay').waitFor({state:'detached'});};
  await page.getByRole('button',{name:'Подарки',exact:true}).click();
  assert.equal(await page.locator('.daily-prize').count(),14);
  await page.locator('[data-day="14"]').evaluate(el=>Promise.all(el.getAnimations().map(animation=>animation.finished)));
  assert.ok(await page.locator('.daily-list').evaluate(el=>{
    const [first,second,third]=el.children;
    return first.offsetTop===second.offsetTop&&second.offsetTop===third.offsetTop&&first.offsetLeft<second.offsetLeft&&second.offsetLeft<third.offsetLeft;
  }),'Daily gifts are arranged in three cells per row');
  await page.getByRole('button',{name:'Забрать ежедневный подарок'}).click();
  assert.ok((await profile()).owned.includes('boxes:lunar'));assert.equal((await profile()).dailyCount,4);
  await page.getByRole('button',{name:'Надеть Лунное стекло'}).click();
  await page.waitForFunction(()=>JSON.parse(localStorage.getItem('jelly-profile')).selected.boxes==='lunar');
  await page.screenshot({path:'test-results/daily-exclusive.png',animations:'disabled'});await close();
  await page.getByRole('button',{name:'Магазин',exact:true}).click();
  await page.waitForFunction(()=>document.querySelector('[data-category=boxes] .shop-current').textContent.startsWith('Лунное стекло'));
  assert.ok(await page.locator('[data-category=boxes] .shop-arrow.next').isDisabled(),'Shop opens on the equipped last box');
  await page.waitForFunction(()=>document.querySelector('.shop-dialog').getAnimations().every(animation=>animation.playState==='finished'));
  const header=await page.locator('.shop-heading').boundingBox(),quick=await page.locator('.shop-quick-coins').boundingBox();
  assert.ok(quick.y>=header.y+header.height-1&&quick.x>195,'Coin video button stays at the top right under the header');
  const nav=page.getByRole('navigation',{name:'Разделы магазина'}),navPosition=await nav.boundingBox();
  const jump=async(label,id)=>{
    await nav.getByRole('button',{name:label,exact:true}).click();
    await page.waitForFunction(id=>{const el=document.querySelector('.shop-scroll'),target=el.querySelector(`[data-shop-section="${id}"]`);return Math.abs(el.scrollTop-Math.min(el.scrollHeight-el.clientHeight,target.offsetTop-8))<2;},id);
    assert.equal(await nav.getByRole('button',{name:label,exact:true}).getAttribute('aria-current'),'true','The active section follows the completed scroll');
  };
  const sectionsLayout=()=>page.locator('[data-shop-section]').evaluateAll(els=>els.map(el=>({id:el.dataset.shopSection,top:el.offsetTop,height:el.offsetHeight})));
  const fixedSections=await sectionsLayout();
  await jump('Наборы','bundles');
  await page.waitForFunction(()=>document.querySelector('.bundle-card.cozy').getAnimations().every(animation=>animation.playState==='finished'));
  assert.ok(await page.locator('.bundle-card.cozy .sale-ribbon').isVisible(),'A red diagonal deal ribbon is visible');
  await page.screenshot({path:'test-results/shop-offers-before.png',animations:'disabled'});
  await page.getByRole('button',{name:'Купить Уютный набор за 1800'}).click();
  assert.equal(await coins(),3200);assert.equal((await profile()).shakeTokens,3);
  for(const key of ['skins:fuzzies','backgrounds:sunset','boxes:rose'])assert.ok((await profile()).owned.includes(key));
  assert.ok(await page.locator('.bundle-card.cozy .primary-button').isDisabled());
  assert.deepEqual(await sectionsLayout(),fixedSections,'Buying a bundle leaves every section in place');
  await page.screenshot({path:'test-results/shop-offers.png'});
  await jump('Монеты','supplies');
  await page.getByRole('button',{name:'Купить 5 встрясок за 500'}).click();assert.equal(await coins(),2700);assert.equal((await profile()).shakeTokens,8);
  await watch(page.locator('.supply-card.coins .supply-video'));assert.equal(await coins(),2700);assert.equal((await profile()).coinVideo,1);
  await watch(page.locator('.supply-card.coins .supply-video'));assert.equal(await coins(),3000);assert.equal((await profile()).coinVideo,0);
  assert.deepEqual(await nav.boundingBox(),navPosition,'Section navigation stays fixed while scrolling and buying');
  assert.deepEqual(await sectionsLayout(),fixedSections,'Purchasing supplies leaves every section in place');
  await close();
  await page.getByRole('button',{name:'Настройки',exact:true}).click();await page.getByRole('button',{name:'Начать заново',exact:true}).click();await page.getByRole('dialog').getByRole('button',{name:'Начать заново',exact:true}).click();await page.locator('.overlay').waitFor({state:'detached'});
  assert.equal(Number(await page.locator('.shake-button>b').textContent()),11,'Restart keeps the purchased bank plus three free shakes');
  await page.reload({waitUntil:'networkidle'});await page.locator('.loading').waitFor({state:'detached'});
  assert.equal((await profile()).shakeTokens,8);assert.equal(await coins(),3000);
  await page.getByRole('button',{name:'Подарки',exact:true}).click();assert.equal(await page.getByRole('button',{name:'Забрать ежедневный подарок'}).count(),0,'Reload cannot reclaim today’s prize');await close();
  for(let i=0;i<4;i++)await page.getByRole('button',{name:/Встряхнуть/}).click();
  assert.equal((await profile()).shakeTokens,7,'Free shakes are used before consuming the persistent bank');assert.equal(await coins(),3000);
  await page.close();
  const finalDay=await browser.newPage({viewport:{width:320,height:568},isMobile:true,hasTouch:true});
  finalDay.on('pageerror',e=>errors.push(e.message));finalDay.on('response',r=>{if(r.status()>=400)errors.push(`${r.status()}: ${r.url()}`);});
  await finalDay.clock.install({time:new Date('2026-10-05T12:00:00Z')});
  await finalDay.addInitScript(()=>{
    if(localStorage.getItem('final-day-seeded'))return;
    localStorage.setItem('final-day-seeded','true');
    localStorage.setItem('jelly-profile',JSON.stringify({daily:'2026-10-04',dailyCount:13}));
  });
  await finalDay.goto(base,{waitUntil:'networkidle'});await finalDay.locator('.loading').waitFor({state:'detached'});
  await finalDay.getByRole('button',{name:'Подарки',exact:true}).click();
  const finalPrize=finalDay.locator('[data-day="14"]');
  await finalPrize.getByRole('button',{name:'Забрать ежедневный подарок'}).click();
  assert.equal(await finalDay.locator('.daily-week-progress').textContent(),'14 / 14 подарков');
  assert.equal(await finalDay.locator('.daily-prize.received').count(),14,'Last claim leaves the whole cycle complete for today');
  assert.ok(await finalDay.locator('.daily-list').evaluate(el=>{
    const [first,second,third]=el.children;
    return first.offsetTop===second.offsetTop&&first.offsetLeft<second.offsetLeft&&third.offsetTop>first.offsetTop;
  }),'Small screens use two cells per row');
  await finalPrize.getByRole('button',{name:'Надеть Кристаллики'}).click();
  await finalDay.waitForFunction(()=>JSON.parse(localStorage.getItem('jelly-profile')).selected.skins==='crystals');
  await finalDay.screenshot({path:'test-results/daily-final-320.png',animations:'disabled'});
  await finalDay.reload({waitUntil:'networkidle'});await finalDay.locator('.loading').waitFor({state:'detached'});
  await finalDay.getByRole('button',{name:'Подарки',exact:true}).click();
  assert.equal(await finalDay.getByRole('button',{name:'Забрать ежедневный подарок'}).count(),0);
  await finalDay.clock.setSystemTime(new Date('2026-10-06T12:00:00Z'));
  await finalDay.evaluate(()=>window.dispatchEvent(new Event('focus')));
  const firstPrize=finalDay.locator('[data-day="1"]');
  await firstPrize.getByRole('button',{name:'Забрать ежедневный подарок'}).click();
  assert.equal(await finalDay.locator('.daily-week-progress').textContent(),'1 / 14 подарков');
  assert.equal(await finalDay.evaluate(()=>JSON.parse(localStorage.getItem('jelly-profile')).dailyCount),15);
  assert.equal(await finalDay.getByTestId('coins').textContent(),'25');
  await finalDay.close();
  console.log('✓ real exclusive daily prize, equipped shop entry, fixed top navigation, one-time bundles, persistent shake packs and two-view coin packs');
}
