import assert from 'node:assert/strict';
import { chromium } from '@playwright/test';
import { installYandexMock } from './yandex-mock.mjs';
const base=process.env.GAME_URL||'http://localhost:5173/';
const browser=await chromium.launch({...(process.env.CHROMIUM_PATH?{executablePath:process.env.CHROMIUM_PATH}:{}),headless:true,args:['--no-sandbox']});
try {
  const page=await browser.newPage({viewport:{width:390,height:720},locale:'en-US',isMobile:true,hasTouch:true});
  const errors=[];page.on('pageerror',error=>errors.push(error.message));
  await installYandexMock(page,{language:'ru',manualAds:true,startPaused:true,cloud:{jellySave:{version:1,updatedAt:Date.now(),best:400,coins:250,settings:{muted:false,language:'it'}}}});
  await page.addInitScript(()=>{
    const OriginalAudio=window.Audio;
    window.__music=[];
    window.Audio=function(...args){const media=new OriginalAudio(...args);window.__music.push(media);return media;};
  });
  let release;
  const gate=new Promise(resolve=>{release=resolve;});
  await page.route('**/countryside.webp',async route=>{await gate;await route.continue();});
  await page.goto(base,{waitUntil:'domcontentloaded'});
  await page.locator('.loading').waitFor();
  assert.equal(await page.locator('html').getAttribute('lang'),'ru','SDK language overrides navigator and cloud settings');
  assert.equal(await page.getByTestId('coins').getAttribute('data-coins'),'250','Cloud data is hydrated before constructing the world');
  assert.equal(await page.evaluate(()=>window.__sdkMock.calls.filter(call=>call.method==='ready').length),0,'Resources still loading');
  release();await page.locator('.loading').waitFor({state:'detached'});
  assert.equal(await page.evaluate(()=>window.__sdkMock.calls.filter(call=>call.method==='ready').length),0,'Startup advertisement still pauses the platform');
  assert.ok(await page.locator('.scene').evaluate(el=>el.inert));
  assert.ok(await page.evaluate(()=>window.__music.every(media=>media.paused)),'Startup ad stays silent');
  await page.evaluate(()=>window.__sdkMock.emit('game_api_resume'));
  await page.waitForFunction(()=>window.__sdkMock.calls.some(call=>call.method==='start'));
  assert.equal(await page.evaluate(()=>window.__sdkMock.calls.filter(call=>call.method==='init').length),1);
  assert.equal(await page.evaluate(()=>window.__sdkMock.calls.filter(call=>call.method==='on').length),2);
  const ready=await page.evaluate(()=>window.__sdkMock.calls.filter(call=>call.method==='ready'));
  assert.equal(ready.length,1);assert.deepEqual(ready[0].args[0],{loading:false,inert:false,canvas:true});
  const widths=[];
  for(const height of [844,720,640]){
    await page.setViewportSize({width:390,height});await page.waitForTimeout(100);
    widths.push(await page.locator('.header').evaluate(el=>el.getBoundingClientRect().width));
    const scene=await page.locator('.scene').boundingBox();assert.ok(scene.y>=-1&&scene.y+scene.height<=height+1);
  }
  assert.ok(widths.every(width=>Math.abs(width-390)<1),'Phone UI keeps full width as the bottom banner reduces height');
  await page.setViewportSize({width:390,height:720});
  await page.getByRole('button',{name:'Баланс монет'}).click();
  await page.waitForTimeout(100);
  const stops=await page.evaluate(()=>window.__sdkMock.calls.filter(call=>call.method==='stop').length);
  assert.equal(stops,1,'Opening a menu stops real gameplay once');
  await page.getByRole('button',{name:/150 монет.*За короткое видео/}).click();
  await page.locator('.mock-platform-ad').waitFor();
  assert.ok(await page.evaluate(()=>window.__music.every(media=>media.paused)),'Rewarded advertisement pauses streaming music');
  await page.evaluate(()=>window.__sdkMock.ad.finish(false));await page.locator('.ad-overlay').waitFor({state:'detached'});
  assert.equal(await page.getByTestId('coins').getAttribute('data-coins'),'250','Closing without reward grants nothing');
  assert.equal(await page.evaluate(()=>window.__sdkMock.calls.filter(call=>call.method==='start').length),1,'Closing an ad does not resume gameplay behind the menu');
  await page.getByRole('button',{name:/150 монет.*За короткое видео/}).click();await page.locator('.mock-platform-ad').waitFor();
  await page.evaluate(()=>window.__sdkMock.ad.finish(true));await page.locator('.ad-overlay').waitFor({state:'detached'});
  assert.equal(await page.getByTestId('coins').getAttribute('data-coins'),'400','Repeated onRewarded callbacks grant only once');
  await page.locator('.dialog-close').click();await page.locator('.overlay').waitFor({state:'detached'});
  await page.waitForFunction(()=>window.__sdkMock.calls.filter(call=>call.method==='start').length===2);
  const canvas=page.locator('canvas');await canvas.dispatchEvent('keydown',{key:'Enter'});await page.waitForTimeout(100);
  await page.evaluate(()=>window.__sdkMock.emit('game_api_pause'));await page.waitForTimeout(100);
  const paused=await canvas.evaluate(el=>el.toDataURL());await canvas.dispatchEvent('keydown',{key:'Enter'});await page.waitForTimeout(300);
  assert.equal(await canvas.evaluate(el=>el.toDataURL()),paused,'Physics and input remain frozen during platform pause');
  const metrics=await page.evaluate(()=>window.__sdkMock.calls.filter(call=>['start','stop'].includes(call.method)).map(call=>call.method));
  assert.deepEqual(metrics,['start','stop','start'],'Platform events emit no duplicate gameplay metrics');
  await page.evaluate(()=>window.__sdkMock.emit('game_api_resume'));await page.waitForTimeout(200);
  assert.notEqual(await canvas.evaluate(el=>el.toDataURL()),paused,'Physics resumes after platform resume');
  await page.getByRole('button',{name:'Настройки',exact:true}).click();assert.equal(await page.getByRole('switch',{name:'Анимации'}).count(),0);
  await page.screenshot({path:'test-results/yandex-mobile-banner.png'});
  assert.deepEqual(errors,[]);await page.close();
  const local=await browser.newPage({locale:'ru-RU'});await local.goto(base);await local.locator('.loading').waitFor({state:'detached'});
  await local.getByRole('button',{name:'Баланс монет'}).click();await local.getByRole('button',{name:/150 монет.*За короткое видео/}).click();
  await local.waitForTimeout(500);assert.equal(await local.getByTestId('coins').getAttribute('data-coins'),'0','No SDK means no fake advertisement or reward');assert.equal(await local.locator('.ad-overlay').count(),0);await local.close();
  console.log('✓ SDK bootstrap/cloud ordering, platform language, startup ad, real ready timing, paused physics/input/music, rewarded callbacks, menu state, mobile banner resize and standalone fallback');
} finally {await browser.close();}
